mode: 0 ## GNSS positioning mode, 0: single, 1:DGPS/DGNSS, 2: kinematic

frequency: 1 ## number of frequency (1:L1,2:L1+L2,3:L1+L2+L5)

soltype: 2 ## type of solution (0:forward,1:backward,2:combined)

satellites: ## all used gnss-systems
    - GPS
    - GLONASS
    - Galileo
    - SBAS

precise_ephemeris: false # use precise satellite orbit solution (SP3) (true/false)

elevationmask: 0 ## min. elevation of satellites to be used in deg