mode: 0 ## GNSS positioning mode, 0: single, 1:DGPS/DGNSS, 2: kinematic

frequency: 1 ## number of frequency (1:L1,2:L1+L2,3:L1+L2+L5)

soltype: 2 ## type of solution (0:forward,1:backward,2:combined)

satellites: ## all used gnss-systems (GPS, GLONASS, Galileo, SBAS)
    - GPS
    - BeiDou
    - QZSS

precise_ephemeris: true # use precise satellite orbit solution (SP3) (true/false)

ionosphere_correction: 5 # (0: off, 1: broadcast, 2: SBAS , 5: IONEX TEC)

elevationmask: 0 ## min. elevation of satellites to be used in deg
